fix(parameters): fix _transform_and_cache_get_parameters_response
was passing positional arguments to transform_value in the wrong order,
making the latter fail miserably with

    TransformParameterError: Unable to transform value using "the value"

because value was being passed as the expected transform argument.
Use keyword arguments instead and cover this with a test.