refactor(parser): add from __future__ import annotations (#4983)
* refactor(parser): add from __future__ import annotations

and update code according to ruff rules TCH, UP006, UP007, UP037 and
FA100.

* Fix type alias with Python 3.8

See https://bugs.python.org/issue45117

* Fix pydantic not working with Python 3.8

    TypeError: You have a type annotation 'str | None' which makes use
    of newer typing features than are supported in your version of Python.
    To handle this error, you should either remove the use of new syntax
    or install the `eval_type_backport` package.

* Update ruff.toml

Configure lint.per-file-ignores in ruff.toml instead of adding a

    # ruff: noqa: FA100

line to each file.

---------

Co-authored-by: Leandro Damascena <lcdama@amazon.pt>